spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
com:
  example:
    upload:
      path: C:\\upload

server:
  port: 9000

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
